In [3]:
import sys
print(sys.executable)
print(sys.version)
# print the TensorFlow version

/Users/beam/2026_spring/IoT_Pipline_2026/ML/tf-env/bin/python
3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]


In [4]:
import tensorflow as tf
import numpy as np
print("TF:", tf.__version__)

TF: 2.20.0


In [5]:
# 1) Scalars, vectors, matrices, tensors
scalar = tf.constant(7) # rank-0
vector = tf.constant([10, 20, 30]) # rank-1
matrix = tf.constant([[1., 2.], [3., 4.]]) # rank-2
tensor = tf.constant([[[1],[2]], [[3],[4]]]) # rank-3 (2x2x1)
print(scalar.shape, vector.shape, matrix.shape, tensor.shape)

() (3,) (2, 2) (2, 2, 1)


In [ ]:
# 2) Dtypes and casting
x = tf.constant([1.7, 7.4]) # float32 default
y = tf.constant([7, 10]) # int32 default
x16 = tf.cast(x, tf.float16) # reduced precision floats
y32 = tf.cast(y, tf.float32) # cast ints → floats

#tf.cast: Used to convert data types.

TensorFlow often uses float32 for deep learning.

Float16 is lighter and faster (especially on GPUs) but less accurate.

int32 is commonly used for indexes/labels; to calculate mean/gradients, it's usually necessary to convert to float.

In [ ]:
# 3) Indexing and shaping
rank2 = tf.constant([[10, 7], [3, 4]])
last_col = rank2[:, -1] # column slice, #Get all rows in the last column
expanded = tf.expand_dims(rank2, -1) # add channel-like axis, Adds a new dimension to a tensor (often used to add a "channel" dimension to an image).
squeezed = tf.squeeze(expanded, axis=-1) #Remove dimensions of size 1 to simplify the tensor.

In [ ]:
# 4) Broadcasting & basic ops
A = tf.constant([[10., 7.], [3., 4.]]) 
print("A+10:\n", A + 10)
print("A*2:\n", A * 2)

A+10:
 tf.Tensor(
[[20. 17.]
 [13. 14.]], shape=(2, 2), dtype=float32)
A*2:
 tf.Tensor(
[[20. 14.]
 [ 6.  8.]], shape=(2, 2), dtype=float32)


In [9]:
# 5) Matrix multiplication rules (inner dims match)
X = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32) # (3x2)
Y = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32) # (3x2)
XtY = tf.matmul(X, tf.transpose(Y)) # (3x2) @ (2x3) -> (3x3)

In [10]:
# 6) Aggregations
E = tf.constant(np.random.randint(0, 100, size=10))
print("min:", tf.reduce_min(E).numpy(),
"max:", tf.reduce_max(E).numpy(),
"mean:", tf.reduce_mean(tf.cast(E, tf.float32)).numpy(),
"sum:", tf.reduce_sum(E).numpy())

min: 6 max: 97 mean: 60.1 sum: 601


In [ ]:
import tensorflow as tf
import numpy as np
print("TF:", tf.__version__)
# 1) Scalars, vectors, matrices, tensors
scalar = tf.constant(7) # rank-0
vector = tf.constant([10, 20, 30]) # rank-1
matrix = tf.constant([[1., 2.], [3., 4.]]) # rank-2
tensor = tf.constant([[[1],[2]], [[3],[4]]]) # rank-3 (2x2x1)
print(scalar.shape, vector.shape, matrix.shape, tensor.shape)
# 2) Dtypes and casting
x = tf.constant([1.7, 7.4]) # float32 default
y = tf.constant([7, 10]) # int32 default
x16 = tf.cast(x, tf.float16) # reduced precision floats
y32 = tf.cast(y, tf.float32) # cast ints → floats
# 3) Indexing and shaping
rank2 = tf.constant([[10, 7], [3, 4]])
last_col = rank2[:, -1] # column slice
expanded = tf.expand_dims(rank2, -1) # add channel-like axis
squeezed = tf.squeeze(expanded, axis=-1)
# 4) Broadcasting & basic ops
A = tf.constant([[10., 7.], [3., 4.]])
print("A+10:\n", A + 10)
print("A*2:\n", A * 2)
# 5) Matrix multiplication rules (inner dims match)
X = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32) # (3x2)
Y = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32) # (3x2)
XtY = tf.matmul(X, tf.transpose(Y)) # (3x2) @ (2x3) -> (3x3)
# 6) Aggregations
E = tf.constant(np.random.randint(0, 100, size=10))
print("min:", tf.reduce_min(E).numpy(),
"max:", tf.reduce_max(E).numpy(),
"mean:", tf.reduce_mean(tf.cast(E, tf.float32)).numpy(),
"sum:", tf.reduce_sum(E).numpy())
# 7) One-hot encoding
idx = tf.constant([0, 1, 2, 3])
oh = tf.one_hot(idx, depth=4)
# 8) NumPy interop
arr = np.array([3., 7., 10.])
t = tf.constant(arr) # NumPy -> Tensor
back_to_np = t.numpy() # Tensor -> NumPy
print("OK")

# tf.one_hot: Converts category indices (e.g., [0, 1, 2]) into binary vectors (e.g., 0 to [1, 0, 0, 0]). This is a common data preparation technique for classification problems.

TF: 2.20.0
() (3,) (2, 2) (2, 2, 1)
A+10:
 tf.Tensor(
[[20. 17.]
 [13. 14.]], shape=(2, 2), dtype=float32)
A*2:
 tf.Tensor(
[[20. 14.]
 [ 6.  8.]], shape=(2, 2), dtype=float32)
min: 3 max: 85 mean: 48.7 sum: 487
OK


Goal for these code: Get acquainted with the data language that Deep Learning uses.

Deep Learning doesn't learn through words or meanings; it learns through:
- NUMBERS
- HOW TO ARRANGE NUMBERS (shapes)
- HOW TO TRANSFORM NUMBERS (matrix multiplication)

Everything in Deep Learning is a tensor:
1 number is scalar
1 list is vector
1 table is matrix
Multiple tables is tensor
When we feed data into AI, it doesn't know if it's an image, a house, or music, it only sees tensor + shape.